import Foundation

/// Generated by scripts/record-docker-image-digests.sh — do not edit.
public enum DockerProductImageDigests: Sendable {
    public static let worker = DockerImageDigest(rawValue: "sha256:686c54118b75056b7ca9af17697516fc242e65b7a8da0e43bb6c0a35f31e8052")
}
