import Foundation

/// Generated by scripts/record-docker-image-digests.sh for logs/audit.
/// Runtime does not require the local image id to match this value.
public enum DockerProductImageDigests: Sendable {
    public static let worker = DockerImageDigest(rawValue: "sha256:3988b3f87dc9f1f8738cbfca9a5835caf3950d1fd728524e72d82f5ad1cd89fe")
}
