import Foundation

/// Generated by scripts/record-docker-image-digests.sh — do not edit.
public enum DockerProductImageDigests: Sendable {
    public static let worker = DockerImageDigest(rawValue: "sha256:d686d16d5fb8fe0a54a1eb9bb9c8a27763b5d80145ad330c5205536d73afdda6")
}
