#!/usr/bin/env swift
import CryptoKit
import Foundation

/// Regenerates `ScriptExecContract.generated.swift` from bundled script_exec JSON.
/// `--check` exits 1 when the committed fingerprint does not match the JSON files
/// or when the JSON no longer satisfies the bundled schemas.

let repoRoot = URL(fileURLWithPath: CommandLine.arguments[0])
    .resolvingSymlinksInPath()
    .deletingLastPathComponent()
    .deletingLastPathComponent()

let resources = repoRoot
    .appendingPathComponent("packages/Structure/Sources/Contract/Resources")

let sources: [(relative: String, url: URL)] = [
    "schemas/script-exec-contract.schema.json",
    "schemas/guest-runtime.schema.json",
    "schemas/hop-event.schema.json",
    "schemas/envelope-list.schema.json",
    "contracts/script-exec-contract.json",
].map { relative in
    (relative, resources.appendingPathComponent(relative))
}

let generatedURL = repoRoot
    .appendingPathComponent("packages/Structure/Sources/Contract/Generated/ScriptExecContract.generated.swift")

func jsonObject(_ url: URL) throws -> [String: Any] {
    let data = try Data(contentsOf: url)
    guard let object = try JSONSerialization.jsonObject(with: data) as? [String: Any] else {
        throw ScriptError("\(url.lastPathComponent) is not a JSON object.")
    }
    return object
}

func requireKeys(_ object: [String: Any], _ keys: [String], file: String) throws {
    for key in keys where object[key] == nil {
        throw ScriptError("\(file) is missing required key \(key).")
    }
}

func validateGraph() throws {
    let contractSchema = try jsonObject(resources.appendingPathComponent("schemas/script-exec-contract.schema.json"))
    let contract = try jsonObject(resources.appendingPathComponent("contracts/script-exec-contract.json"))
    try requireKeys(contract, contractSchema["required"] as? [String] ?? [], file: "script-exec-contract.json")
    let rulesSchema = (contractSchema["properties"] as? [String: Any])?["rules"] as? [String: Any]
    try requireKeys(
        contract["rules"] as? [String: Any] ?? [:],
        rulesSchema?["required"] as? [String] ?? [],
        file: "script-exec-contract.json rules"
    )
    let checks = (contract["review"] as? [String: Any])?["checks"] as? [[String: Any]] ?? []
    if checks.isEmpty {
        throw ScriptError("script-exec-contract.json review.checks must not be empty.")
    }
    let pluginFactorySchema = (contractSchema["properties"] as? [String: Any])?["plugin_factory"] as? [String: Any]
    try requireKeys(
        contract["plugin_factory"] as? [String: Any] ?? [:],
        pluginFactorySchema?["required"] as? [String] ?? [],
        file: "script-exec-contract.json plugin_factory"
    )
}

func fingerprint() throws -> String {
    var joined = Data()
    for source in sources {
        let data = try Data(contentsOf: source.url)
        joined.append(Data(source.relative.utf8))
        joined.append(0)
        joined.append(data)
        joined.append(0)
    }
    return SHA256.hash(data: joined).map { String(format: "%02x", $0) }.joined()
}

func generatedSource(hash: String) -> String {
    """
    // Automatically generated by scripts/generate-script-exec-contract.swift. DO NOT EDIT.

    /// SHA-256 of script_exec protocol JSON and schemas. `swift test` fails when this is stale.
    public enum ScriptExecContractFingerprint: Sendable {
        public static let sha256 = "\(hash)"
        public static let sourceFiles: [String] = [
    \(sources.map { "        \"\($0.relative)\"," }.joined(separator: "\n"))
        ]
    }

    """
}

struct ScriptError: Error, CustomStringConvertible {
    let description: String
    init(_ description: String) { self.description = description }
}

do {
    try validateGraph()
} catch {
    fputs("\(error)\n", stderr)
    exit(1)
}

let hash = try fingerprint()
let check = CommandLine.arguments.contains("--check")
if check {
    let existing = try String(contentsOf: generatedURL, encoding: .utf8)
    if !existing.contains("public static let sha256 = \"\(hash)\"") {
        fputs("script_exec contract fingerprint is stale. Run scripts/generate-script-exec-contract.swift\n", stderr)
        exit(1)
    }
    exit(0)
}

try FileManager.default.createDirectory(
    at: generatedURL.deletingLastPathComponent(),
    withIntermediateDirectories: true
)
try generatedSource(hash: hash).write(to: generatedURL, atomically: true, encoding: .utf8)
print("Wrote \(generatedURL.path) sha256=\(hash)")
