#!/usr/bin/env bash
# Builds the unified Go worker image and records its image id for logs/audit.
# Runtime readiness is the OCI binaries label (crawler,extractor,search), not this id.
# Docker assigns a new image id on every local build, so this file is not a gate.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

IMAGE="derrick-worker:go-v1"
docker build -f docker/worker/Dockerfile -t "$IMAGE" .

DIGEST="$(docker image inspect --format '{{.Id}}' "$IMAGE")"
OUT="packages/Structure/Sources/DockerRunnerXPC/DockerProductImageDigests.generated.swift"

cat >"$OUT" <<EOF
import Foundation

/// Generated by scripts/record-docker-image-digests.sh — do not edit.
public enum DockerProductImageDigests: Sendable {
    public static let worker = DockerImageDigest(rawValue: "$DIGEST")
}
EOF

echo "Recorded worker digest $DIGEST"
